/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmasalud.partederecepcion;

import farmasalud.ConsultasGenerales;
import farmasalud.jtable.jtCabeceraParteDeRecepcion;
import farmasalud.jtable.jtDetalleRecepcion;
import farmasalud.operaciones.OManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Francisco Palacio
 */
public class FElegirCabeceraParteRecepcion extends javax.swing.JFrame {
    private  jtCabeceraParteDeRecepcion tablaCabeceraRecepcion;    
    private OManager manager;
    private ConsultasGenerales consultas;
    /**
     * Creates new form FElegirCabeceraParteRecepcion
     */
    public FElegirCabeceraParteRecepcion() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        manager=new OManager();
        consultas=ConsultasGenerales.obtenerInstacia();
        cargarTabla();
        btnAbrir.setEnabled(false);
        habilitarBotonAbrir();   
    }

    private void habilitarBotonAbrir() { 
      consultas.habilitarBotonAbrir(tableCabeceraParte,btnAbrir);  
    }

    private void cargarTabla() {
        tablaCabeceraRecepcion=new jtCabeceraParteDeRecepcion(manager);
        tablaCabeceraRecepcion.updateTable("BO");
        tableCabeceraParte.getTableHeader().setReorderingAllowed(false);
        tableCabeceraParte.setModel(tablaCabeceraRecepcion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCabeceraParte = new javax.swing.JTable();
        btnAbrir = new javax.swing.JButton();

        tableCabeceraParte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCabeceraParte.setRowHeight(25);
        tableCabeceraParte.setRowMargin(5);
        tableCabeceraParte.setSelectionBackground(new java.awt.Color(0, 153, 51));
        jScrollPane1.setViewportView(tableCabeceraParte);

        btnAbrir.setText("ABRIR");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
      int row= tableCabeceraParte.getSelectedRow();
      int idCabecera=Integer.valueOf(tableCabeceraParte.getValueAt(row, 0).toString());
      FParteDeRecepcion abrir=  new FParteDeRecepcion(idCabecera);
      abrir.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FElegirCabeceraParteRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FElegirCabeceraParteRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FElegirCabeceraParteRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FElegirCabeceraParteRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FElegirCabeceraParteRecepcion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCabeceraParte;
    // End of variables declaration//GEN-END:variables

  
}
