/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmasalud.pedidosSucursales;

import farmasalud.operaciones.ODetallesPedidos;
import farmasalud.operaciones.OManager;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import farmasalud.atributosclases.ADetallePedidos;
import farmasalud.jtable.jtDetallePedidos;

/**
 *
 * @author Francisco Palacio
 */
public class FDetallesPedidosSucursales extends javax.swing.JFrame {
      private OManager manager;;
      private jtDetallePedidos tabla;
     
    /**
     * Creates new form DetallesPedidosSucursales
     * @param numero
     */
    public FDetallesPedidosSucursales(int numero) {
        initComponents();
        llenarTabla(numero);
        this.setTitle("DETALLES PEDIDO NRO: "+numero);
        this.setLocationRelativeTo(null);
            
    }

    private void llenarTabla(int numero) {
        manager= new OManager();
        tabla=new jtDetallePedidos(manager);
        tabla.update(numero);
        jTableDetallePedidos.setModel(tabla);
        jTableDetallePedidos.getTableHeader().setReorderingAllowed(false);
    }
    

    private FDetallesPedidosSucursales() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDetallePedidos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableDetallePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDetallePedidos.setRowHeight(25);
        jTableDetallePedidos.setRowMargin(5);
        jTableDetallePedidos.setSelectionBackground(new java.awt.Color(0, 153, 51));
        jTableDetallePedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableDetallePedidosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDetallePedidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableDetallePedidosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDetallePedidosMouseReleased
  
    }//GEN-LAST:event_jTableDetallePedidosMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDetallesPedidosSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDetallesPedidosSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDetallesPedidosSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDetallesPedidosSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
                   
        java.awt.EventQueue.invokeLater(new Runnable() {
         @Override
         public void run() {
          new FDetallesPedidosSucursales().setVisible(true);
                }
                
            
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDetallePedidos;
    // End of variables declaration//GEN-END:variables
}
