/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmasalud.pedidoCotizacion;

import farmasalud.operaciones.OManager;
import farmasalud.atributosclases.ACabeceraCotizacion;
import farmasalud.atributosclases.ACabeceraPedidos;
import farmasalud.atributosclases.ADetalleConsolidado;
import farmasalud.atributosclases.ADetalleCotizacion;
import farmasalud.atributosclases.UsuarioActivo;

import farmasalud.obtenerFecha;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 *
 * @author Francisco Palacio
 */
public class FPanelCotizacion extends javax.swing.JFrame {
    
    private FListadoCotizacionesPorEstado abrir;
    private final OManager traer;
    private ArrayList<ACabeceraPedidos> cabeceraPedidos;

    /**
     * Creates new form PanelCotizacion
     */
    public FPanelCotizacion() {
        this.traer = new OManager();
        initComponents();
        
        jButtonBO.setEnabled(false);
        jButtonAU.setEnabled(false);
        btnDesierta.setEnabled(false);
        jButtonAN.setEnabled(false);
        jButtonEN.setEnabled(false);
        jButtonCT.setEnabled(false);
        habilitarBotonNuevaCotizacion();
        
        habilitarBotonesEstados();
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    private void habilitarBotonNuevaCotizacion() {
        cabeceraPedidos = traer.getCabeceraPedidos().obtenerPedidosXEstado("AU");
        if (!cabeceraPedidos.isEmpty()) {
            jButton5.setEnabled(true);
        } else {
            jButton5.setEnabled(false);
        }
    }
    
    private void habilitarBotonesEstados() {
        List<String> estados = traer.getCabeceraCotizacion().obtenerTodos().stream().
                collect(Collectors.groupingBy(s -> s.getEstadoCotizacion())).entrySet()
                .stream().map(e -> e.getKey()).collect(Collectors.toList());
        System.out.println(estados);
        estados.forEach((String e) -> {
            System.out.println(e);
            switch (e) {
                case "BO":
                    jButtonBO.setEnabled(true);
                    System.out.println("bo");
                    break;
                case "AU":
                    jButtonAU.setEnabled(true);
                    System.out.println("au");
                    break;
                case "EN":
                    jButtonEN.setEnabled(true);
                    System.out.println("en");
                    break;
                case "CT":
                    jButtonCT.setEnabled(true);
                    break;
                case "AN":
                    jButtonAN.setEnabled(true);
                    break;
                case "DE":
                    btnDesierta.setEnabled(true);
                    break;

            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonBO = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButtonEN = new javax.swing.JButton();
        jButtonAU = new javax.swing.JButton();
        jButtonAN = new javax.swing.JButton();
        jButtonCT = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        btnDesierta = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Estados "));

        jButtonBO.setText("EN BORRADOR");
        jButtonBO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBOActionPerformed(evt);
            }
        });

        jButtonEN.setText("ENVIADO");
        jButtonEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonENActionPerformed(evt);
            }
        });

        jButtonAU.setText("ENVIAR");
        jButtonAU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAUActionPerformed(evt);
            }
        });

        jButtonAN.setText("ANULADO");
        jButtonAN.setPreferredSize(new java.awt.Dimension(233, 40));
        jButtonAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonANActionPerformed(evt);
            }
        });

        jButtonCT.setText("COTIZADO");
        jButtonCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCTActionPerformed(evt);
            }
        });

        btnDesierta.setText("DESIERTA");
        btnDesierta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesiertaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButtonAU, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButtonBO, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCT, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDesierta, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButtonEN, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addComponent(jSeparator7)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonAN, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButtonAU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButtonEN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButtonCT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDesierta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pedidos Cotizacion"));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consulta_php.gif"))); // NOI18N
        jButton5.setText("Nuevo pedido cotizacion");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(69, 69, 69))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("PEDIDOS DE COTIZACION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Estados ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBOActionPerformed
        abrir = new FListadoCotizacionesPorEstado("BO", "Cotizaciones en estado borrador");
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBOActionPerformed

    private void jButtonENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonENActionPerformed
        abrir = new FListadoCotizacionesPorEstado("EN", "Cotizaciones en estado enviado");
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonENActionPerformed

    private void jButtonAUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAUActionPerformed
        abrir = new FListadoCotizacionesPorEstado("AU", "Cotizaciones en estado autorizado");
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAUActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        FSeleccionarCabeceraPedidos abrir = new FSeleccionarCabeceraPedidos(cabeceraPedidos);
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonANActionPerformed
        abrir = new FListadoCotizacionesPorEstado("AN", "Cotizaciones en estado anulado");
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonANActionPerformed

    private void jButtonCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCTActionPerformed
        abrir = new FListadoCotizacionesPorEstado("CT", "Cotizaciones en estado cotizado");
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCTActionPerformed

    private void btnDesiertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesiertaActionPerformed
        abrir = new FListadoCotizacionesPorEstado("DE", "Cotizaciones en estado desierto");
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDesiertaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPanelCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPanelCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPanelCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPanelCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPanelCotizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesierta;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAN;
    private javax.swing.JButton jButtonAU;
    private javax.swing.JButton jButtonBO;
    private javax.swing.JButton jButtonCT;
    private javax.swing.JButton jButtonEN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
